# Project Name
TARGET = KeyboardLayoutTest

# Sources
CPP_SOURCES = main.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core

# Add this line to your Makefile
CPP_STANDARD = -std=gnu++17

# Core Makefile Loader
include $(LIBDAISY_DIR)/core/Makefile